### ISSUE TITLE
Feature request: prioritize

### ISSUE THREAD

**Issue by p1r473** [virgilhuxley/pathmerge#1]
Hi,
Great tool. Id love the ability to sort, but also prioritize. 
I want `/usr/local/bin` to come before `/usr/bin`
Best way I can figure to do this right now is to remove it from the path then manually add it back in to the front

new_path=$(echo "$PATH" | tr ':' '\n' | grep -v "^/usr/local/bin$" | paste -sd: -)
export PATH="$new_path"
export PATH="$(/usr/local/bin/pathmerge --path "$PATH")"
export PATH="/usr/local/bin:$PATH"

**Comment by virgilhuxley** [comment]
I am not sure I am capturing the nuance of the complexity in your `new_path=` expression.  
Forgive my naive response if it misunderstand your request. Tell me if I missed something.

Question:
Does this represent an abstract of what you're trying to accomplish?

```bash
old_path="/priority2/priority1:/priority3"
``` 
And your desired outcome is?:
```bash
new_path="/priority1:/priority2:/priority3"
```


If yes - Answer: This can already be done rather easily
```bash
old_path="/priority2:/priority1:/priority3"
new_path="$(pathmerge --path "/priority1:"${old_path}")"
```
`pathmerge` will see the path string of "/priority1:/priority2:/priority1:/priority3",  
hold onto the first "/priority1", then prune any subsequent occurrence of "/priority1"

If no - please provide a more exact test string and the desired resulting output.


Commentary:
- I do like the idea of a directive to request an entry to be pruned
- I also like the idea of an additional "--prepend" flag who's argument is to be prepended to the resulting output

Commentary applicable _if_ the **answer** above solve your problem:
I need a good reason to add those additional features.  
If there's a problem that would be more easily solved by a repo change, rather-than a inconsistent shell-hack, let me know.

**Comment by virgilhuxley** [comment]
In the event you were looking to utilize both sort and prioritize at the same time that can similarly be accomplished with an additional call to pathmerge.

In the following example, the paths would be sorted, but item "/priorityZ" will be placed in the first index.

```bash
old_path="/priority3:/priorityZ:/priority2:/priority1"
new_path="$( pathmerge --path /priorityZ:$(pathmerge --sort --path "${old_path}") )"
```

The result of `new_path` is `/priorityZ:/priority1:/priority2:/priority3`.  
The inner call to pathmerge will output a string: `/priority1:/priority2:/priority3:/priorityZ`.  
The outer call to pathmerge will then perform an operation similar to the one mentioned int he first comment I made: `/priorityZ:/priority1:/priority2:/priority3`

The `new_path1 variable is not as elegantly constructed, but that's more of a syntax problem to fix.  
I think that would be better handled by adding a flag that accepts stdin as the path. This would allow for piping calls rather than wrapping in nested subshells.

Feedback would be appreciated.

**Comment by p1r473** [comment]
That works perfect thank you so much
`PATH=$(pathmerge --path /usr/local/bin:$(pathmerge --sort --path "${PATH}"))`
